# --------------------------------------------------------
# 渲染配置

render:
  scale: 100 # 渲染精度

# --------------------------------------------------------
# 定时任务配置

signin_time: 0 10 0 * * ?
anns_push_time: 0 0/10 * * * ?
# --------------------------------------------------------

auto_signin: false # 自动签到开关
anns_push: false # 公告推送开关
