# --------------------------------------------------------
# 渲染与视觉配置
# --------------------------------------------------------

render:
  scale: 100 # 渲染精度 (50-200)

panel_version: 1 # 面板版本: 1 (窄版) 或 2 (宽版)

yuantu_pile: true # 立绘原图开关
yuantu_bg: true # 背景原图开关

# --------------------------------------------------------
# 定时任务配置
# --------------------------------------------------------

signin_time: 0 10 0 * * ? # 自动签到执行时间 (Cron表达式)
anns_push_time: 0 0/10 * * * ? # 公告推送检测频率

# --------------------------------------------------------
# 功能开关
# --------------------------------------------------------

auto_signin: false # 自动签到开关
anns_push: false # 公告推送开关

signin_switch: true # 签到功能：是否全局开启手动签到命令

# --------------------------------------------------------
# 角色数据配置
# --------------------------------------------------------

multi_daily: true # 多角色体力开关
multi_daily_forward: 3 # 转发阈值：超过几个角色后将结果转为合并记录形式转发
